version: '3.7'
volumes:
  laravel_redis_data:
  laravel_mysql_data:
networks:
  laravel-network:
    driver: bridge
services:
  mysql:
    container_name: laravel-db
    restart: on-failure
    volumes:
      - laravel_mysql_data:/var/lib/mysql
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=laraveldb
    ports:
      - "3306:3306"
    networks:
      laravel-network:
        aliases:
          - mysql.laravel
  redis:
    container_name: laravel-redis
    restart: on-failure
    volumes:
      - laravel_redis_data:/data:rw
    image: redis:5.0.8
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      laravel-network:
        aliases:
          - redis.laravel

  php:
    container_name: "laravel-php-fpm"
    image: csighub.tencentyun.com/qidian/dsshop_php:dev
    depends_on:
      - redis
      - mysql
    build:
      context: ./docker/php-fpm/
    volumes:
      - ./laravel:/var/www/html/
    restart: on-failure
    networks:
      laravel-network:
        aliases:
          - php-fpm.laravel

  backend:
    container_name: "laravel-backend"
    depends_on:
      - php
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./laravel:/var/www/html/:rw
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/:rw
      - ./docker/nginx/ssl:/etc/nginx/ssl/:rw
      - ./laravel/storage/logs/:/var/log/nginx/:rw
    restart: on-failure
    networks:
      laravel-network:
        aliases:
          - backend.laravel
          - local.laravel.com
